# Dockerfile generated by GeneXus (.NET Core)
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
LABEL maintainer="Renzo <Renzo@example.com>"
WORKDIR /app
COPY ["ibm/20200730123835", "/app"]
ENTRYPOINT ["dotnet", "bin/GxNetCoreStartup.dll"]
